Repository chesdenis/net-courses, pull requests merged in 2018-04, with the labels that each got.

#3 Ruslan Kudaybergenov Task2
  Task2 - Delegates/Ruslan Kudaybergenov/Ruslan Kudaybergenov.sln
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Abstractions/IBoard.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Abstractions/IDrawing.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Abstractions/IShowMessage.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Abstractions/IUserInputs.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/App.config
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Implementations/Board.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Implementations/Drawing.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Implementations/Input.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Implementations/ShowMessage.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Program.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Properties/AssemblyInfo.cs
  Task2 - Delegates/Ruslan Kudaybergenov/Task2/Task2.csproj
Labels: review in progress

#15 Valentin-Tyrgin-task3
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension.sln
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension/App.config
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension/Extension.cs
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension/Extension.csproj
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension/Program.cs
  Task3 - Extensions/Valentin Tyrgin Task3/Extension/Extension/Properties/AssemblyInfo.cs
Labels: review in progress

#14 Valentin-Tyrgin-task2
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates.sln
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/App.config
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/Delegates.csproj
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/DrawObjects/Board.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/DrawObjects/HorizontalLine.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/DrawObjects/Point.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/DrawObjects/VerticalLine.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/IBoard.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/Program.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/Properties/AssemblyInfo.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/UserIntaraction.cs
  Task2 - Delegates/Valentin Tyrgin Task2/Delegates/Delegates/Utils.cs
Labels: review in progress

#7 finished task 2
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/App.config
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/BoardDrawing.ConsoleApp.csproj
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/BoardWithListOfPoints.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/HorizontalLine.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/Point.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/ProccesUserChoice.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/Registry.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/ShowMessageToUser.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Implementations/VerticalLine.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Program.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.ConsoleApp/Properties/AssemblyInfo.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/Abstractions/IBoard.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/Abstractions/IProccesUserChoice.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/Abstractions/IRegistry.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/Abstractions/IShowMessageToUser.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/App.config
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/BoardDrawing.Core.csproj
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/ProgramLogic.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.Core/Properties/AssemblyInfo.cs
  Task2 - Delegates/Vladislav Chesnov/BoardDrawing.sln
Labels: almost ready, review in progress

#10 Made task2
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Core/Class1.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Core/Core.csproj
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Core/Properties/AssemblyInfo.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Drawing.ConsoleApp.csproj
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Implementations/Board.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Implementations/ConsoleAppRegistry.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Implementations/ConsoleOutput.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Implementations/ConsoleProcessUserActions.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Implementations/ItemsBuilder.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Program.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.ConsoleApp/Properties/AssemblyInfo.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Abstractions/IBoard.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Abstractions/IItemsBuilder.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Abstractions/IProcessUserActions.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Abstractions/IRegistry.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Abstractions/IShowMessageToUser.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Drawing.Core.csproj
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/GameLogic.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.Core/Properties/AssemblyInfo.cs
  Task2 - Delegates/Nikita_Nuttunen/Delegates/Drawing.sln
Labels: almost ready, review in progress

#16 task2, ver.1
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/App.config
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Delegates.ConsoleApp.csproj
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Implementations/Board.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Implementations/Drawing.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Implementations/ProcessUserInput.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Implementations/Registry.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Implementations/ShowMessageToUser.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Program.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.ConsoleApp/Properties/AssemblyInfo.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Abstractions/IBoard.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Abstractions/IDrawing.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Abstractions/IProcessUserInput.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Abstractions/IRegistry.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Abstractions/IShowMessageToUser.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/App.config
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Delegates.Core.csproj
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/GameLogic.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.Core/Properties/AssemblyInfo.cs
  Task2 - Delegates/tatiana-klimenko/Delegates/Delegates.sln
Labels: almost ready, review in progress

#17 Egor plisov task2
  Task2 - Delegates/Egor_Plisov/Simple_Drawer.sln
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/App.config
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/DrawOnBoard.cs
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/IBoard.cs
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/Program.cs
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/Properties/AssemblyInfo.cs
  Task2 - Delegates/Egor_Plisov/Simple_Drawer/Simple_Drawer.csproj
Labels: almost ready, review in progress

#30 task 2 - delegates
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/App.config
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ConsoleBoard.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ConsoleBoard/Board.csproj
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ConsoleBoard/Class1.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ConsoleBoard/Properties/AssemblyInfo.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ConsoleInterface.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/EPAM_homework_delegates.csproj
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/EPAM_homework_delegates.sln
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/Program.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/ProgramLogic.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/Properties/AssemblyInfo.cs
  Task2 - Delegates/Pavel Makarikhin/EPAM_homework_delegates/Registry.cs
Labels: review in progress

#35 Tasks done
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Delegates.ConsoleApp.csproj
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Implementations/ConsoleBoard.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Implementations/ConsolePoint.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Implementations/ConsoleProcessUserChoice.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Implementations/ConsoleShowMessageToUser.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Implementations/Registry.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Program.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.ConsoleApp/Properties/AssemblyInfo.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/IBoard.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/IPoint.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/IProcessUserChoice.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/IRegistry.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/IShowMessageToUser.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Abstractions/Types.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/AppLogic.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Delegates.Core.csproj
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.Core/Properties/AssemblyInfo.cs
  Task2 - Delegates/Danil_Dukhovnikov/Delegates.sln
  Task3 - Extensions/Danil_Dukhovnikov/Extensions.sln
  Task3 - Extensions/Danil_Dukhovnikov/ExtensionsForString.ConsoleApp/Extensions.cs
  Task3 - Extensions/Danil_Dukhovnikov/ExtensionsForString.ConsoleApp/ExtensionsForString.ConsoleApp.csproj
  Task3 - Extensions/Danil_Dukhovnikov/ExtensionsForString.ConsoleApp/Program.cs
  Task3 - Extensions/Danil_Dukhovnikov/ExtensionsForString.ConsoleApp/Properties/AssemblyInfo.cs
  Task4 - Partials/Danil_Dukhovnikov/T4Example.sln
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleConsoleApp/App.config
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleConsoleApp/Program.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleConsoleApp/Properties/AssemblyInfo.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleConsoleApp/T4ExampleConsoleApp.csproj
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/CodeGenerationTemplate.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/CodeGenerationTemplate.tt
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/Partials/Artist.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/Partials/Book.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/Properties/AssemblyInfo.cs
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/Resources/XmlDataExample.xml
  Task4 - Partials/Danil_Dukhovnikov/T4ExampleCore/T4ExampleCore.csproj
Labels: review in progress

#44 Anna zakharchenko task3
  Task3 - Extensions/Anna Zakharchenko/StringExtantion/StringExtantion.sln
  Task3 - Extensions/Anna Zakharchenko/StringExtantion/StringExtantion/App.config
  Task3 - Extensions/Anna Zakharchenko/StringExtantion/StringExtantion/Program.cs
  Task3 - Extensions/Anna Zakharchenko/StringExtantion/StringExtantion/Properties/AssemblyInfo.cs
  Task3 - Extensions/Anna Zakharchenko/StringExtantion/StringExtantion/StringExtantion.csproj
Labels: changes required, review in progress

#51 RuslanKudaybergenovTask6
  Task6 - Lambda/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6.sln
  Task6 - Lambda/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6/App.config
  Task6 - Lambda/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6/Program.cs
  Task6 - Lambda/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6/Properties/AssemblyInfo.cs
  Task6 - Lambda/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6/RuslanKudaybergenovTask6.csproj
Labels: changed

#53 Task 6 is ready for checking.
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas.sln
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas/App.config
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas/Lambdas.csproj
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas/NumberGenerator.cs
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas/Program.cs
  Task6 - Lambda/Vladimir_Bogdan/Lambdas/Lambdas/Properties/AssemblyInfo.cs
Labels: changed
